(part "ABS04W-32_768KHZ-6-D2-T5"
    (packageRef "ABS04W32768KHZ6D2T5")
    (interface
        (port "1" (symbPinId 1) (portName "CRYSTAL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CRYSTAL_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "815-04W-32.768-6-D2T")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ABS04W-32.768KHZ-6-D2-T5?qs=lc2O%252BfHJPVZbxXtU7CitfQ%3D%3D")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ABS04W-32.768KHZ-6-D2-T5")
    (property "Description" "32.768 kHz +/-20ppm Crystal 6pF 130 kOhms 4-SMD, No Lead")
    (property "Datasheet_Link" "https://abracon.com/datasheets/ABS04W.pdf")
    (property "symbolName1" "ABS04W-32_768KHZ-6-D2-T5")
)
